[tool.poetry]
name = "resto-reserve"
version = "0.1.0"
description = ""
authors = ["katja <gorbunovakatja530@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django-perms = "^2.1.0"
Django = "^5.2.7"
djangorestframework = "^3.16.1"
python-dotenv = "^1.1.1"
pillow = "^11.3.0"
coverage = "^7.11.0"
drf-spectacular = "^0.28.0"
stripe = "^13.0.1"
requests = "^2.32.5"
celery = "^5.5.3"
psycopg2-binary = "^2.9.11"
gunicorn = "^23.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
pytest-cov = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
