[tool.poetry]
name = "resto-reserve"
version = "0.1.0"
description = ""
authors = ["katja <gorbunovakatja530@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django-perms = "^2.1.0"
Django = "^5.2.3"
djangorestframework = "^3.16.0"
python-dotenv = "^1.1.0"
pillow = "^11.2.1"
coverage = "^7.8.0"
drf-spectacular = "^0.28.0"
stripe = "^12.0.0"
drf-yasg = "^1.21.8"
requests = "^2.32.4"
celery = "^5.5.3"
psycopg2-binary = "^2.9.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
