# Generated by Django 5.2.4 on 2025-07-09 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="name",
            field=models.CharField(default="Гость", max_length=100, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="booking",
            name="phone",
            field=models.CharField(default="", max_length=20, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
