# Generated by Django 5.2.4 on 2025-07-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_name_booking_phone_alter_booking_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название блюда"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Цена"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("starters", "Закуски"),
                            ("soups", "Супы"),
                            ("main_courses", "Основные блюда"),
                            ("desserts", "Десерты"),
                            ("drinks", "Напитки"),
                            ("wines", "Вино"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="menu/",
                        verbose_name="Фото блюда",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Доступно"),
                ),
                (
                    "is_special",
                    models.BooleanField(
                        default=False, verbose_name="Специальное предложение"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order", "name"],
            },
        ),
    ]
