# Generated by Django 5.2.4 on 2025-07-09 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_alter_booking_options_alter_menuitem_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
