# Generated by Django 5.2.4 on 2025-08-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_delete_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Сумма предоплаты",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="deposit_paid",
            field=models.BooleanField(default=False, verbose_name="Предоплата внесена"),
        ),
        migrations.AddField(
            model_name="booking",
            name="deposit_paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата внесения предоплаты"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="has_preorder",
            field=models.BooleanField(default=False, verbose_name="Есть предзаказ"),
        ),
        migrations.AddField(
            model_name="booking",
            name="preorder_items",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Предзаказанные блюда"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="preorder_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Сумма предзаказа",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает предоплаты"),
                    ("paid", "Предоплата внесена"),
                    ("confirmed", "Подтверждено"),
                    ("completed", "Завершено"),
                ],
                default="pending",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
    ]
