# Generated by Django 5.2.4 on 2025-08-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_booking_deposit_amount_booking_deposit_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает предоплаты"),
                    ("paid", "Предоплата внесена"),
                    ("confirmed", "Подтверждено"),
                    ("completed", "Завершено"),
                    ("cancelled", "Отменено"),
                ],
                default="confirmed",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
    ]
