# Generated by Django 5.2.4 on 2025-08-18 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0007_alter_booking_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deposit_confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата подтверждения администратором"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="deposit_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_deposits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подтвердил администратор",
            ),
        ),
    ]
