# Generated by Django 5.2.4 on 2025-07-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menucategory",
            name="icon",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Иконка Bootstrap"
            ),
        ),
    ]
